# Generated by Django 5.2.8 on 2026-02-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DangerousGoods',
            fields=[
                ('dangerous_good', models.IntegerField(db_column='shop_good.id', primary_key=True, serialize=False)),
                ('good', models.CharField(db_column='good_name', max_length=255)),
                ('amount', models.CharField(db_column='good_amount', max_length=255)),
            ],
            options={
                'db_table': 'dangerous_goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodIncome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(db_column='users_income', max_length=255)),
                ('date', models.DateField(db_column='date_income', max_length=255)),
                ('orders', models.FloatField(db_column='orders_income', max_length=255)),
            ],
            options={
                'db_table': 'good_income',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adress', models.CharField(db_column='user_adres', max_length=255)),
                ('email', models.EmailField(db_column='user_email', max_length=255)),
                ('phonenumber', models.TextField(db_column='user_phonenumber', max_length=255)),
                ('date', models.DateField(db_column='cart_date', max_length=255)),
            ],
            options={
                'db_table': 'user_orders',
                'managed': False,
            },
        ),
    ]
