# Generated by Django 5.2.8 on 2026-02-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('username', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'order_report',
                'managed': False,
            },
        ),
    ]
