# Generated by Django 5.2.8 on 2026-02-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_orderreport'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderreport',
            table='orders_report',
        ),
    ]
