# Generated by Django 5.2.8 on 2026-02-12 11:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_refresh_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDangerousGoods',
            fields=[
                ('dangerous_good', models.IntegerField(db_column='id', db_index=True)),
                ('good', models.CharField(db_column='good_name', max_length=255)),
                ('amount', models.CharField(db_column='good_amount', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical dangerous goods',
                'verbose_name_plural': 'historical dangerous goodss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGoodIncome',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('user', models.CharField(db_column='users_income', max_length=255)),
                ('date', models.DateField(db_column='date_income', max_length=255)),
                ('orders', models.FloatField(db_column='orders_income', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical good income',
                'verbose_name_plural': 'historical good incomes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrderReport',
            fields=[
                ('order_id', models.IntegerField(db_column='order_id', db_index=True)),
                ('date', models.DateField(db_column='order_date')),
                ('username', models.CharField(db_column='username')),
                ('product_name', models.CharField(db_column='product_name')),
                ('price_at_purchase', models.DecimalField(db_column='price_at_purchase', decimal_places=2, max_digits=255)),
                ('total', models.DecimalField(db_column='total', decimal_places=2, max_digits=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order report',
                'verbose_name_plural': 'historical order reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUserOrders',
            fields=[
                ('adress', models.CharField(db_column='user_adres', max_length=255)),
                ('email', models.EmailField(db_column='user_email', db_index=True, max_length=255)),
                ('phonenumber', models.TextField(db_column='user_phonenumber', max_length=255)),
                ('date', models.DateField(db_column='cart_date', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user orders',
                'verbose_name_plural': 'historical user orderss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
