# Generated by Django 5.2.8 on 2026-02-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_historicaldangerousgoods_historicalgoodincome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgoodincome',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorderreport',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluserorders',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalDangerousGoods',
        ),
        migrations.DeleteModel(
            name='HistoricalGoodIncome',
        ),
        migrations.DeleteModel(
            name='HistoricalOrderReport',
        ),
        migrations.DeleteModel(
            name='HistoricalUserOrders',
        ),
    ]
