FROM python:latest

RUN apt-get update 

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ENV PROMETHEUS_MULTIPROC_DIR=/app/metrics_data

RUN mkdir -p /app/metrics_data

EXPOSE 8000

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
